In [1]:
import pandas as pd

In [ ]:
# Đọc các bảng

In [2]:
customers = pd.read_csv("../clean/customers.csv", dtype = {"customer_zip_code_prefix" : str})

In [3]:
geolocation = pd.read_csv("../clean/geolocation.csv", dtype={"geolocation_zip_code_prefix": str})

In [83]:
order_items = pd.read_csv("../clean/order_items.csv", parse_dates = ["shipping_limit_date"])

In [178]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

In [179]:
orders = pd.read_csv("../clean/orders.csv", parse_dates = date_cols)

In [180]:
payments = pd.read_csv("../clean/payments.csv")

In [181]:
product_category = pd.read_csv("../clean/product_category.csv")

In [182]:
products = pd.read_csv("../clean/products.csv")

In [183]:
review_date_cols = ["review_creation_date",	"review_answer_timestamp"]

In [184]:
reviews = pd.read_csv("../clean/reviews.csv", parse_dates = review_date_cols)

In [185]:
sellers = pd.read_csv("../clean/sellers.csv", dtype={"seller_zip_code_prefix": str})

In [186]:
tables = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "orders": orders,
    "payments": payments,
    "product_category": product_category,
    "products": products,
    "reviews": reviews,
    "sellers": sellers
}

In [187]:
for name,df in tables.items() :
    print(f"\n{name} : ")
    print(df.head())

customers :
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

  customer_zip_code_prefix          customer_city customer_state
0                    14409                 Franca             SP
1                    09790  Sao Bernardo Do Campo             SP
2                    01151              Sao Paulo             SP
3                    08775        Mogi Das Cruzes             SP
4                    13056               Campinas             SP

geolocation :
  geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                       01001       -23.550227       -46.634039
1                       01002       -23.547657       -46.634991
2                       01003       -23.549000       -46.635582
3                       01004       -23.549829       -46.634792
4                       01005       -23.549547       -46.636406

  geolocation_city geolocation_state
0        Sao Paulo                SP
1        Sao Paulo                SP
2        Sao Paulo                SP
3        Sao Paulo                SP
4        Sao Paulo                SP

order_items :
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

  shipping_limit_date   price  freight_value
0 2017-09-19 09:45:35   58.90          13.29
1 2017-05-03 11:05:13  239.90          19.93
2 2018-01-18 14:48:30  199.00          17.87
3 2018-08-15 10:10:18   12.99          12.79
4 2017-02-13 13:57:51  199.90          18.14

orders :
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp   order_approved_at  \
0    delivered      2017-10-02 10:56:33 2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37 2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49 2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06 2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39 2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0                    2017-10-18
1                    2018-08-13
2                    2018-09-04
3                    2017-12-15
4                    2018-02-26

payments :
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

product_category :
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

products :
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

reviews :
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score                             review_comment_message  \
0             4                                         No Comment
1             5                                         No Comment
2             5                                         No Comment
3             5              Recebi bem antes do prazo estipulado.
4             5  Parabéns lojas lannister adorei comprar pela I...

  review_creation_date review_answer_timestamp review_sentiment
0           2018-01-18     2018-01-18 21:46:59         Positive
1           2018-03-10     2018-03-11 03:05:13         Positive
2           2018-02-17     2018-02-18 14:36:24         Positive
3           2017-04-21     2017-04-21 22:02:06         Positive
4           2018-03-01     2018-03-02 10:26:53         Positive

sellers :
                          seller_id seller_zip_code_prefix        seller_city  \
0  3442f8959a84dea7ee197c632cb2df15                  13023           Campinas
1  d1b65fc7debc3361ea86b5f14c68d2e2                  13844         Mogi Guacu
2  ce3ad9de960102d0677a81f5d0bb7b2d                  20031     Rio De Janeiro
3  c0f3eea2e14555b6faeea3dd58c1b1c3                  04195          Sao Paulo
4  51a04a8a6bdcb23deccc82b0b80742cf                  12914  Braganca Paulista

  seller_state
0           SP
1           SP
2           RJ
3           SP
4           SP

# DIM CUSTOMERS

In [188]:
customers.sort_values(by = "customer_zip_code_prefix", ascending = True).head(1000)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
23914,7ae2a9337aa4bc799723511faa1d6830,0c1a20644f0dc126c3eaff8dbc1bd12c,01003,Sao Paulo,SP
11747,a09edf8c1e842e94805a206b3d73eed5,968f6d2f674977d88a4b445a5117ccd8,01004,Sao Paulo,SP
23990,ee9b73e88afb4904ee2322cfc89cf638,095e7c124c5c1ccb1eb9f731152eae6a,01004,Sao Paulo,SP
81634,15d7dbcd027b5b24866db33e2b819021,ddab5650ba76e2fa2d7e25ed3343bd92,01005,Sao Paulo,SP
34298,f3e31afdae80581be48ce94e7b0f3366,ded4351942c7fc292b88e5b090af2b46,01005,Sao Paulo,SP
...,...,...,...,...,...
79078,d40d86343d1aa6a8a3ce63ab5a19d6b4,113b5c1fb03a238d9131fc1af666f70f,01327,Sao Paulo,SP
96690,bdbec4574e600193aa141d27a2fec1e8,4344098be86475dfeb8cfa56252c2f2a,01327,Sao Paulo,SP
91301,1733bd74b2d3aee8edc1ace540ac52ba,601fc330c69bcd236b91da084d7bb210,01328,Sao Paulo,SP
90893,3ab92b803f7011fe479bc1502d40f1d5,7c75e010e637f4f32ac425dd7982a9d9,01328,Sao Paulo,SP
69865,3afb4376b76a9615a6c548f25dcb251e,78e25992c2a0fa7cc3828c3e777ead0d,01328,Sao Paulo,SP

In [189]:
geolocation.head(5)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01001,-23.550227,-46.634039,Sao Paulo,SP
1,01002,-23.547657,-46.634991,Sao Paulo,SP
2,01003,-23.549000,-46.635582,Sao Paulo,SP
3,01004,-23.549829,-46.634792,Sao Paulo,SP
4,01005,-23.549547,-46.636406,Sao Paulo,SP

In [190]:
# Join 2 bảng customer và geolocation
cus_join = pd.merge(customers, geolocation, left_on = "customer_zip_code_prefix", right_on = "geolocation_zip_code_prefix", how = "inner")

In [191]:
#  Lây sra các cột cần thiết cho dim_customer
dim_customer = cus_join[["customer_id",
                        "customer_unique_id",
                        "customer_city",
                        "customer_state",
                        "customer_zip_code_prefix",
                        "geolocation_lat",
                        "geolocation_lng"
                        ]]

In [192]:
dim_customer.head()

,customer_id,customer_unique_id,customer_city,customer_state,customer_zip_code_prefix,geolocation_lat,geolocation_lng
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,Franca,SP,14409,-20.499273,-47.396658
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,Sao Bernardo Do Campo,SP,09790,-23.728396,-46.542250
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,Sao Paulo,SP,01151,-23.531309,-46.656690
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,Mogi Das Cruzes,SP,08775,-23.500670,-46.186348
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,Campinas,SP,13056,-22.975708,-47.143140

In [193]:
dim_customer["customer_state"].unique()

<StringArray>
['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE',
 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE',
 'RR']
Length: 27, dtype: str

In [194]:
state_map = {
    "AC": "Acre",
    "AL": "Alagoas",
    "AP": "Amapa",
    "AM": "Amazonas",
    "BA": "Bahia",
    "CE": "Ceara",
    "DF": "Distrito Federal",
    "ES": "Espirito Santo",
    "GO": "Goias",
    "MA": "Maranhao",
    "MT": "Mato Grosso",
    "MS": "Mato Grosso do Sul",
    "MG": "Minas Gerais",
    "PA": "Para",
    "PB": "Paraiba",
    "PR": "Parana",
    "PE": "Pernambuco",
    "PI": "Piaui",
    "RJ": "Rio de Janeiro",
    "RN": "Rio Grande do Norte",
    "RS": "Rio Grande do Sul",
    "RO": "Rondonia",
    "RR": "Roraima",
    "SC": "Santa Catarina",
    "SP": "Sao Paulo",
    "SE": "Sergipe",
    "TO": "Tocantins"
}

In [195]:
# Map state
dim_customer["customer_state_name"] = (
    dim_customer["customer_state"]
    .map(state_map)
)

In [196]:
dim_customer.head()

,customer_id,customer_unique_id,customer_city,customer_state,customer_zip_code_prefix,geolocation_lat,geolocation_lng,customer_state_name
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,Franca,SP,14409,-20.499273,-47.396658,Sao Paulo
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,Sao Bernardo Do Campo,SP,09790,-23.728396,-46.542250,Sao Paulo
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,Sao Paulo,SP,01151,-23.531309,-46.656690,Sao Paulo
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,Mogi Das Cruzes,SP,08775,-23.500670,-46.186348,Sao Paulo
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,Campinas,SP,13056,-22.975708,-47.143140,Sao Paulo

In [274]:
dim_customer.to_csv("../data_warehouse/dim_customer.csv", index = False, encoding = "utf-8")

# DIM PRODUCT

In [197]:
products.head(1)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0

In [198]:
product_category.head(1)

  product_category_name product_category_name_english
0          beleza_saude                 health_beauty

In [199]:
# Join 2 bảng products và product_category 
prd_join =  pd.merge(products, product_category, on = "product_category_name", how = "inner")

In [200]:
# Tạo cột volumn
prd_join["product_volume_cm3"] = prd_join["product_length_cm"] * prd_join["product_height_cm"] * prd_join["product_width_cm"]

In [201]:
prd_join.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,product_volume_cm3
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery,2240.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art,10800.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure,2430.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby,2704.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares,4420.0

In [202]:
product_dtypes = {
    "product_name_lenght": "int64",
    "product_description_lenght": "int64",
    "product_photos_qty": "int64",
    "product_weight_g": "int64",
    "product_length_cm": "int64",
    "product_height_cm": "int64",
    "product_width_cm": "int64",
    "product_volume_cm3": "int64"
}

In [203]:
# Chuyển đổi kiểu dữ liệu các cột thông tin sản phẩm (chiều cao,cân nặng,....)
prd_join = prd_join.astype(product_dtypes)

In [204]:
# Đổi tên các cột lỗi 
prd_join.rename(columns = {"product_description_lenght" : "product_description_length", 
                           "product_name_lenght" : "product_name_length", 
                           "product_category_name_english" : "product_category"}, inplace = True)

In [205]:
# Chọn các cột cần cho dim_product
dim_product = prd_join[["product_id",
                        "product_category",
                        "product_name_length",
                        "product_description_length",
                        "product_photos_qty",
                        "product_weight_g",
                        "product_length_cm",
                        "product_height_cm",
                        "product_width_cm",
                        "product_volume_cm3"
                        ]]

In [206]:
dim_product.head()

,product_id,product_category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40,287,1,225,16,10,14,2240
1,3aa071139cb16b67ca9e5dea641aaa2f,art,44,276,1,1000,30,18,20,10800
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,46,250,1,154,18,9,15,2430
3,cef67bcfe19066a932b7673e239eb23d,baby,27,261,1,371,26,4,26,2704
4,9dc1a7de274444849c219cff195d0b71,housewares,37,402,4,625,20,17,13,4420

In [1]:
dim_product.to_csv("../data_warehouse/dim_product.csv", index = False, encoding = "utf-8")

NameError: name 'dim_product' is not defined

# DIM SELLER

In [207]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,Sao Paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP

In [208]:
sellers["seller_state"].unique()

<StringArray>
['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN', 'MT', 'CE',
 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM', 'PA']
Length: 23, dtype: str

In [209]:
# Map state
sellers["seller_state"] = sellers["seller_state"].map(state_map)

In [ ]:
# Chọn ra các cột cần thiết cho dim seller
dim_seller =  sellers[["seller_id",
                    "seller_city",
                    "seller_state",
                    "seller_zip_code_prefix"
                    ]]

In [ ]:
dim_seller.head()

,seller_id,seller_city,seller_state,seller_zip_code_prefix
0,3442f8959a84dea7ee197c632cb2df15,Campinas,Sao Paulo,13023
1,d1b65fc7debc3361ea86b5f14c68d2e2,Mogi Guacu,Sao Paulo,13844
2,ce3ad9de960102d0677a81f5d0bb7b2d,Rio De Janeiro,Rio de Janeiro,20031
3,c0f3eea2e14555b6faeea3dd58c1b1c3,Sao Paulo,Sao Paulo,04195
4,51a04a8a6bdcb23deccc82b0b80742cf,Braganca Paulista,Sao Paulo,12914

In [ ]:
dim_seller.to_csv("../data_warehouse/dim_seller.csv", index = False, encoding = "utf-8")

# DIM DATE

In [212]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [213]:
order_date = orders.copy()

In [214]:
# Lấy date trong purchase date
order_date["full_date"] = order_date["order_purchase_timestamp"].dt.strftime("%Y-%m-%d")

In [215]:
# Tạo ra id từ cột purchase date 
order_date["date_id"] = order_date["order_purchase_timestamp"].dt.strftime("%Y%m%d")

In [216]:
# Tạo ra năm, tháng, quý, ngày
order_date["year"] = order_date["order_purchase_timestamp"].dt.year
order_date["month"] = order_date["order_purchase_timestamp"].dt.month
order_date["quarter"] = order_date["month"].apply(lambda x : 1 if x in [1,2,3] 
                                                        else 2 if x in [4,5,6]
                                                        else 3 if x in [7,8,9]
                                                        else 4)
order_date["day"] = order_date["order_purchase_timestamp"].dt.day

In [217]:
# Lấy tuần 
order_date["week"] = (order_date["day"]/7 + 1).astype(int)

In [218]:
# Lấy thứ
order_date["weekday"] = order_date["order_purchase_timestamp"].dt.day_name()

In [219]:
month_map = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}

In [220]:
# Đổi tên tháng
order_date["month_name"] = order_date["month"].map(month_map)

In [221]:
# Check có phải cuổi tuần không
order_date["is_weekend"] = order_date["weekday"].apply(lambda x : True if x in ["Saturday", "Sunday"] else False)

In [222]:
order_date.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,full_date,date_id,year,month,quarter,day,week,weekday,month_name,is_weekend
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017-10-02,20171002,2017,10,4,2,1,Monday,October,False
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018-07-24,20180724,2018,7,3,24,4,Tuesday,July,False
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018-08-08,20180808,2018,8,3,8,2,Wednesday,August,False
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017-11-18,20171118,2017,11,4,18,3,Saturday,November,True
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018-02-13,20180213,2018,2,1,13,2,Tuesday,February,False

In [223]:
# Chọn các cột cần thiết cho dim date
dim_date = order_date[[
                        "date_id",
                        "full_date",
                        "year",
                        "quarter",
                        "month",
                        "month_name",
                        "week",
                        "day",
                        "weekday",
                        "is_weekend"
                        ]]

In [224]:
dim_date.head()

,date_id,full_date,year,quarter,month,month_name,week,day,weekday,is_weekend
0,20171002,2017-10-02,2017,4,10,October,1,2,Monday,False
1,20180724,2018-07-24,2018,3,7,July,4,24,Tuesday,False
2,20180808,2018-08-08,2018,3,8,August,2,8,Wednesday,False
3,20171118,2017-11-18,2017,4,11,November,3,18,Saturday,True
4,20180213,2018-02-13,2018,1,2,February,2,13,Tuesday,False

In [ ]:
dim_date.to_csv("../data_warehouse/dim_date.csv", index = False, encoding = "utf-8")

# DIM REVIEWS

In [225]:
reviews.head()

,review_id,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp,review_sentiment
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Comment,2018-01-18,2018-01-18 21:46:59,Positive
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Comment,2018-03-10,2018-03-11 03:05:13,Positive
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No Comment,2018-02-17,2018-02-18 14:36:24,Positive
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06,Positive
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53,Positive

In [226]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_message   99201 non-null  str
 4   review_creation_date     99224 non-null  datetime64[us]
 5   review_answer_timestamp  99224 non-null  datetime64[us]
 6   review_sentiment         99224 non-null  str
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 5.3 MB

In [227]:
# Chọn các cột cần thiết cho dim review
dim_review = reviews[[
    "review_id",
    "review_score",
    "review_sentiment",
    "review_comment_message",
    "review_creation_date"
]]

In [228]:
dim_review.head()

,review_id,review_score,review_sentiment,review_comment_message,review_creation_date
0,7bc2406110b926393aa56f80a40eba40,4,Positive,No Comment,2018-01-18
1,80e641a11e56f04c1ad469d5645fdfde,5,Positive,No Comment,2018-03-10
2,228ce5500dc1d8e020d8d1322874b6f0,5,Positive,No Comment,2018-02-17
3,e64fb393e7b32834bb789ff8bb30750e,5,Positive,Recebi bem antes do prazo estipulado.,2017-04-21
4,f7c4243c7fe1938f181bec41a392bdeb,5,Positive,Parabéns lojas lannister adorei comprar pela I...,2018-03-01

# DIM SALES

In [229]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [230]:
# Tạo cột danh mục thanh toán
payments["payment_category"] = payments["payment_installments"].apply(lambda x : "Installment" if x > 1 
                                                                                else "One-time")

In [231]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value,payment_category
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,Installment
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,One-time
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,One-time
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,Installment
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,Installment

In [232]:
# Chọn ra cột cần thiết cho dim_payment
dim_payment = payments[["payment_type",	"payment_installments",	"payment_category"]].drop_duplicates().reset_index(drop = True)

In [233]:
# Tạo cột id
dim_payment["payment_id"] = dim_payment.index + 1

In [234]:
dim_payment = dim_payment[["payment_id", "payment_type",	"payment_installments",	"payment_category"]]

In [235]:
dim_payment.head()

   payment_id payment_type  payment_installments payment_category
0           1  credit_card                     8      Installment
1           2  credit_card                     1         One-time
2           3  credit_card                     2      Installment
3           4  credit_card                     3      Installment
4           5  credit_card                     6      Installment

# FACT SALES

In [236]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [237]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112267 entries, 0 to 112266
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112267 non-null  str
 1   order_item_id        112267 non-null  int64
 2   product_id           112267 non-null  str
 3   seller_id            112267 non-null  str
 4   shipping_limit_date  112267 non-null  datetime64[us]
 5   price                112267 non-null  float64
 6   freight_value        112267 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB

In [238]:
# Join với bảng reviews
fact_join_review = pd.merge(order_items, reviews, on = "order_id", how = "left")

In [239]:
# Join với bảng orders để lấy customer_id
fact_join_order = pd.merge(fact_join_review, orders, on = "order_id", how = "left")

In [240]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value,payment_category
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,Installment
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,One-time
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,One-time
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,Installment
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,Installment

In [241]:
# Join với bảng payments
fact_join_payment = pd.merge(fact_join_order, payments, on = "order_id", how = "left")

In [242]:
# Join với bảng dim_payment để lấy payment_id
fact_join_payment = pd.merge(fact_join_payment, dim_payment, on =  ["payment_type",
                                                                    "payment_installments",	
                                                                    "payment_category"], how = "left")

In [244]:
fact_join_payment.info()

<class 'pandas.DataFrame'>
RangeIndex: 117920 entries, 0 to 117919
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117920 non-null  str
 1   order_item_id                  117920 non-null  int64
 2   product_id                     117920 non-null  str
 3   seller_id                      117920 non-null  str
 4   shipping_limit_date            117920 non-null  datetime64[us]
 5   price                          117920 non-null  float64
 6   freight_value                  117920 non-null  float64
 7   review_id                      116943 non-null  str
 8   review_score                   116943 non-null  float64
 9   review_comment_message         116915 non-null  str
 10  review_creation_date           116943 non-null  datetime64[us]
 11  review_answer_timestamp        116943 non-null  datetime64[us]
 12  review_sentiment               116943 non-null  str
 13  customer_id                    117847 non-null  str
 14  order_status                   117847 non-null  str
 15  order_purchase_timestamp       117847 non-null  datetime64[us]
 16  order_approved_at              117832 non-null  datetime64[us]
 17  order_delivered_carrier_date   116593 non-null  datetime64[us]
 18  order_delivered_customer_date  115261 non-null  datetime64[us]
 19  order_estimated_delivery_date  117847 non-null  datetime64[us]
 20  payment_sequential             117917 non-null  float64
 21  payment_type                   117917 non-null  str
 22  payment_installments           117917 non-null  float64
 23  payment_value                  117917 non-null  float64
 24  payment_category               117917 non-null  str
 25  payment_id                     117917 non-null  float64
dtypes: datetime64[us](8), float64(7), int64(1), str(10)
memory usage: 23.4 MB

In [246]:
fact_join_payment["date_id"] = fact_join_payment["order_purchase_timestamp"].dt.strftime("%Y%m%d")

In [247]:
fact_join_payment.info()

<class 'pandas.DataFrame'>
RangeIndex: 117920 entries, 0 to 117919
Data columns (total 27 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117920 non-null  str
 1   order_item_id                  117920 non-null  int64
 2   product_id                     117920 non-null  str
 3   seller_id                      117920 non-null  str
 4   shipping_limit_date            117920 non-null  datetime64[us]
 5   price                          117920 non-null  float64
 6   freight_value                  117920 non-null  float64
 7   review_id                      116943 non-null  str
 8   review_score                   116943 non-null  float64
 9   review_comment_message         116915 non-null  str
 10  review_creation_date           116943 non-null  datetime64[us]
 11  review_answer_timestamp        116943 non-null  datetime64[us]
 12  review_sentiment               116943 non-null  str
 13  customer_id                    117847 non-null  str
 14  order_status                   117847 non-null  str
 15  order_purchase_timestamp       117847 non-null  datetime64[us]
 16  order_approved_at              117832 non-null  datetime64[us]
 17  order_delivered_carrier_date   116593 non-null  datetime64[us]
 18  order_delivered_customer_date  115261 non-null  datetime64[us]
 19  order_estimated_delivery_date  117847 non-null  datetime64[us]
 20  payment_sequential             117917 non-null  float64
 21  payment_type                   117917 non-null  str
 22  payment_installments           117917 non-null  float64
 23  payment_value                  117917 non-null  float64
 24  payment_category               117917 non-null  str
 25  payment_id                     117917 non-null  float64
 26  date_id                        117847 non-null  str
dtypes: datetime64[us](8), float64(7), int64(1), str(11)
memory usage: 24.3 MB

In [ ]:
# Tạo cột tổng tiền 
fact_join_payment["total_amount"] = fact_join_payment["price"] + fact_join_payment["freight_value"]

In [ ]:
# Tạo cột số ngày giao hàng
fact_join_payment["delivery_days"] = (fact_join_payment["order_delivered_customer_date"] - fact_join_payment["order_purchase_timestamp"]).dt.days

In [252]:
# Tạo cột số ngày để tiếp nhận đơn hàng
fact_join_payment["approval_days"] = (fact_join_payment["order_approved_at"] - fact_join_payment["order_purchase_timestamp"]).dt.days

In [ ]:
# Tạo cột kiểm tra đơn giao muộn
fact_join_payment["is_late_delivery"] = (fact_join_payment["order_delivered_customer_date"] > fact_join_payment["order_estimated_delivery_date"])

In [254]:
# Chọn các cột cần cho bảng fact sales
fact_sales = fact_join_payment[[
    "order_id",
    "customer_id",
    "product_id",
    "seller_id",
    "review_id",
    "payment_id",
    "date_id",
    "order_status",
    "price",
    "freight_value",
    "total_amount",
    "payment_value",
    "delivery_days",
    "approval_days",
    "is_late_delivery"
    ]]

In [257]:
fact_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 117920 entries, 0 to 117919
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          117920 non-null  str
 1   customer_id       117847 non-null  str
 2   product_id        117920 non-null  str
 3   seller_id         117920 non-null  str
 4   review_id         116943 non-null  str
 5   payment_id        117917 non-null  float64
 6   date_id           117847 non-null  str
 7   order_status      117847 non-null  str
 8   price             117920 non-null  float64
 9   freight_value     117920 non-null  float64
 10  total_amount      117920 non-null  float64
 11  payment_value     117917 non-null  float64
 12  delivery_days     115261 non-null  float64
 13  approval_days     117832 non-null  float64
 14  is_late_delivery  117920 non-null  bool
dtypes: bool(1), float64(7), str(7)
memory usage: 12.7 MB

In [260]:
fact_sales = fact_sales.astype({"delivery_days":"Int64", "approval_days":"Int64"})

In [271]:
fact_sales.head()

,order_id,customer_id,product_id,seller_id,review_id,payment_id,date_id,order_status,price,freight_value,total_amount,payment_value,delivery_days,approval_days,is_late_delivery
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,97ca439bc427b48bc1cd7177abe71365,3.0,20170913,delivered,58.90,13.29,72.19,72.19,7,0,False
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,7b07bacd811c4117b742569b04ce3580,4.0,20170426,delivered,239.90,19.93,259.83,259.83,16,0,False
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,0c5b33dea94867d1ac402749e5438e8b,7.0,20180114,delivered,199.00,17.87,216.87,216.87,7,0,False
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,f4028d019cb58564807486a6aaf33817,3.0,20180808,delivered,12.99,12.79,25.78,25.78,6,0,False
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,940144190dcba6351888cafa43f3a3a5,4.0,20170204,delivered,199.90,18.14,218.04,218.04,25,0,False